# Gitleaks configuration for secret scanning
# Enforces the "no secrets in code" policy outlined in APPLICATION_PHASES.md

[allowlist]
  description = "Allowlist for demo/test values and false positives"
  files = [
    # Test and demo files that may contain mock secrets
    '''(?i).*test.*''',
    '''(?i).*spec.*''',
    '''(?i).*mock.*''',
    '''(?i).*example.*''',
    '''(?i).*demo.*''',
    '''(?i).*\.example\..*''',
    '''(?i).*\.template\..*''',
    # Documentation files
    '''(?i).*\.md$''',
    '''(?i).*\.txt$''',
  ]
  
  # Allow demo/placeholder values in local development configs
  regexes = [
    '''demo_key_[a-zA-Z0-9]+''',
    '''placeholder_[a-zA-Z0-9]+''',
    '''test_key_[a-zA-Z0-9]+''',
    '''sk-demo[a-zA-Z0-9]+''',
    '''YOUR_API_KEY_HERE''',
    '''REPLACE_WITH_ACTUAL_KEY''',
  ]

# High entropy string detection
[[rules]]
  id = "entropy-high"
  description = "High entropy strings (potential secrets)"
  regex = '''[a-zA-Z0-9+/]{40,}'''
  entropy = 4.3
  
[[rules]]
  id = "api-key-generic"
  description = "Generic API key patterns"
  regex = '''(?i)(api_key|apikey|api-key|secret|token)\s*[:=]\s*['"][a-zA-Z0-9_\-]{16,}['"]'''
  
[[rules]]
  id = "openai-api-key"
  description = "OpenAI API Key"
  regex = '''sk-[a-zA-Z0-9]{48}'''
  
[[rules]]
  id = "anthropic-api-key"  
  description = "Anthropic API Key"
  regex = '''sk-ant-[a-zA-Z0-9\-_]{90,}'''
  
[[rules]]
  id = "google-api-key"
  description = "Google API Key"
  regex = '''AIza[0-9A-Za-z\\-_]{35}'''
  
[[rules]]
  id = "aws-access-key"
  description = "AWS Access Key ID"
  regex = '''AKIA[0-9A-Z]{16}'''
  
[[rules]]
  id = "aws-secret-key"
  description = "AWS Secret Access Key"
  regex = '''(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z\/+]{40}['"]'''
  
[[rules]]
  id = "jwt-token"
  description = "JWT Token"
  regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''
  
[[rules]]
  id = "database-uri"
  description = "Database connection strings"
  regex = '''(?i)(postgresql|mysql|mongodb)://[a-zA-Z0-9_.-]+:[a-zA-Z0-9_.-]+@[a-zA-Z0-9_.-]+'''
  
[[rules]]
  id = "private-key"
  description = "Private keys"
  regex = '''-----BEGIN [A-Z]+ PRIVATE KEY-----'''
  
[[rules]]
  id = "bearer-token"
  description = "Bearer tokens"
  regex = '''(?i)bearer\s+[a-zA-Z0-9_\-\.=]+'''

# Specific secret patterns for common services
[[rules]]
  id = "github-token"
  description = "GitHub Token"
  regex = '''ghp_[0-9a-zA-Z]{36}'''
  
[[rules]]
  id = "stripe-key"
  description = "Stripe API Key"
  regex = '''sk_live_[0-9a-zA-Z]{24}'''
  
[[rules]]
  id = "sendgrid-key"
  description = "SendGrid API Key"
  regex = '''SG\.[a-zA-Z0-9_\-\.]{66}'''