packages:
  # Mobile applications
  - "apps/*"
  # Backend services
  - "services/*"
  # Shared libraries and packages
  - "packages/*"
  # Development tools
  - "tools/*"

# Catalog configuration for dependency management
catalog:
  # React Native and mobile dependencies
  react: ^18.2.0
  react-native: ^0.73.0
  "@react-navigation/native": ^6.1.0
  "@react-navigation/stack": ^6.3.0
  
  # Backend dependencies
  "@nestjs/core": ^10.0.0
  "@nestjs/common": ^10.0.0
  "@nestjs/platform-express": ^10.0.0
  "@nestjs/typeorm": ^10.0.0
  "@nestjs/jwt": ^10.0.0
  "@nestjs/passport": ^10.0.0
  typeorm: ^0.3.0
  postgres: ^3.4.0
  redis: ^4.6.0
  
  # Shared utilities
  typescript: ^5.3.3
  eslint: ^8.56.0
  prettier: ^3.1.1
  jest: ^29.7.0
  "@types/node": ^20.10.5
  
  # AI and ML libraries
  "@anthropic-ai/sdk": ^0.17.0
  openai: ^4.24.0
  "@google-cloud/aiplatform": ^3.15.0
  
  # Security and monitoring
  "@sentry/node": ^7.92.0
  "@sentry/react-native": ^5.15.0
  helmet: ^7.1.0
  rate-limiter-flexible: ^3.0.0