name: Documentation Build & Deploy

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '*.md'

env:
  NODE_VERSION: '18'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install documentation dependencies
      run: |
        # Install VitePress or similar documentation tool
        npm install -g vitepress
        
    - name: Validate documentation links
      run: |
        # Install markdown link checker
        npm install -g markdown-link-check
        
        # Check all markdown files
        find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*" | xargs markdown-link-check --config .markdown-link-check.json
        
    - name: Generate API documentation
      working-directory: services/backend
      run: |
        npm install
        npm run docs:generate
        
    - name: Build documentation site
      run: |
        # Create docs site structure
        mkdir -p docs-site
        
        # Copy documentation files
        cp -r docs/* docs-site/
        cp README.md docs-site/
        cp CONTRIBUTING.md docs-site/
        
        # Copy API docs
        mkdir -p docs-site/api
        cp -r services/backend/docs/* docs-site/api/
        
    - name: Generate documentation index
      run: |
        cat > docs-site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>HealthCoachAI Documentation</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; }
                .header { border-bottom: 1px solid #eee; padding-bottom: 20px; margin-bottom: 40px; }
                .section { margin-bottom: 30px; }
                .section h2 { color: #333; border-bottom: 1px solid #eee; padding-bottom: 10px; }
                .links { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 20px; }
                .link-card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; text-decoration: none; color: inherit; }
                .link-card:hover { background-color: #f9f9f9; }
                .link-card h3 { margin: 0 0 10px 0; color: #0066cc; }
                .link-card p { margin: 0; color: #666; font-size: 14px; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>HealthCoachAI Documentation</h1>
                <p>Comprehensive documentation for the HealthCoachAI platform</p>
            </div>
            
            <div class="section">
                <h2>Getting Started</h2>
                <div class="links">
                    <a href="README.html" class="link-card">
                        <h3>Project Overview</h3>
                        <p>Introduction to HealthCoachAI and its capabilities</p>
                    </a>
                    <a href="CONTRIBUTING.html" class="link-card">
                        <h3>Contributing Guide</h3>
                        <p>How to contribute to the project</p>
                    </a>
                    <a href="IMPLEMENTATION_PLAN.html" class="link-card">
                        <h3>Implementation Plan</h3>
                        <p>Development phases and milestones</p>
                    </a>
                </div>
            </div>
            
            <div class="section">
                <h2>API Documentation</h2>
                <div class="links">
                    <a href="api/index.html" class="link-card">
                        <h3>REST API</h3>
                        <p>Complete API reference and examples</p>
                    </a>
                    <a href="api/authentication.html" class="link-card">
                        <h3>Authentication</h3>
                        <p>Authentication and authorization guide</p>
                    </a>
                </div>
            </div>
            
            <div class="section">
                <h2>Development</h2>
                <div class="links">
                    <a href="backend/setup.html" class="link-card">
                        <h3>Backend Setup</h3>
                        <p>Setting up the backend development environment</p>
                    </a>
                    <a href="mobile/setup.html" class="link-card">
                        <h3>Mobile Setup</h3>
                        <p>iOS and Android development setup</p>
                    </a>
                </div>
            </div>
            
            <div class="section">
                <h2>Deployment</h2>
                <div class="links">
                    <a href="deployment/environments.html" class="link-card">
                        <h3>Environments</h3>
                        <p>Development, staging, and production environments</p>
                    </a>
                    <a href="deployment/ci_cd.html" class="link-card">
                        <h3>CI/CD Pipeline</h3>
                        <p>Continuous integration and deployment</p>
                    </a>
                </div>
            </div>
        </body>
        </html>
        EOF
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation-site
        path: docs-site/
        
  deploy-docs:
    if: github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Download documentation artifacts
      uses: actions/download-artifact@v3
      with:
        name: documentation-site
        path: docs-site/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        force_orphan: true
        
  validate-openapi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate OpenAPI spec
      run: |
        # Install Swagger CLI
        npm install -g @apidevtools/swagger-cli
        
        # Validate OpenAPI specs
        if [ -f "data/schemas/openapi.yml" ]; then
          swagger-cli validate data/schemas/openapi.yml
        fi
        
        if [ -f "services/backend/openapi/schema.json" ]; then
          swagger-cli validate services/backend/openapi/schema.json
        fi